---
title: "Preparation_Amazon_data"
date: "2022-12-28"
output:
  html_document: 
    number_sections: yes
    fig_caption: yes
    toc: true
    toc_float: 
      collapsed: true
    theme: cerulean
    highlight: kate
    toc_depth: 5
    keep_md: yes
    df_print: paged
---

# Load libraries

```{r warning=FALSE, message=FALSE}
# load libraries
library(tictoc)
library(tidyverse)
library(terra)
library(sf)
library(RColorBrewer)
library(rts)
library(doParallel)
library(parallel)
library(foreach)
library(data.table)
library(tidyterra)
# Plot
library(RColorBrewer)
library(tidyterra)
library(scico)
library(wesanderson)
library(viridis)
library(scales)
library(latex2exp)
library(ggplot2)
```

# Functions

```{r "Functions"}
# Function to save layers
saveLayers = function(dataRast, shapeFile, pathFile, strRemove,
                      x_min=xmin(dataRast), x_max=xmax(dataRast), 
                      y_min=ymin(dataRast), y_max=ymax(dataRast)){
  
  # Iterate all the layers
  for (i in 1:nlyr(dataRast)){
    print(i)
    dataRast.i <- dataRast[[i]]
    # Crop data
    dataRast.basin.i <- mask(dataRast.i, mask = shapeFile) %>%
      crop(ext(x_min, x_max, y_min, y_max))
    # Path of the file
    path <- gsub(strRemove, "", names(dataRast.basin.i)) %>%
      paste0(pathFile, ., ".tif")
    # Save file
    writeRaster(dataRast.basin.i, path, overwrite=TRUE)
    # Clear memory
    gc()
  }
}

# Function to rename layers
renameLayers <- function(dataRast, fileStart, prefix){
  # index of file name in the path
  id.date <- unlist(gregexpr(fileStart, sources(dataRast)[[1]])) + nchar(fileStart)
  # rename layers
  names(dataRast) <- 
    substr(sources(dataRast), id.date, (id.date+50)) %>%
    gsub(".tif", "_1", .) %>%
    as.Date("%Y_%m_%d") %>%
    format(., '%Y_%m') %>%
    paste0(prefix, .)
  
  return(dataRast)
}
# Plot
myPlot <- function(rast, title=''){
  p <- ggplot()  +
    geom_spatraster(data = rast) +
    geom_spatvector(data = amaz.basin.shp$geometry, fill = NA, color = "gray40") +
    scale_x_continuous(labels = function(x) format(x, scientific = T)) +
    scale_y_continuous(labels = function(x) format(x, scientific = T)) +
    coord_sf(datum = pull_crs(rast)) +
    ggtitle(title)  +
    theme_bw()
  return(p)
}
```

# Initialization

```{r}
my.path <- "~/Documents/"

# Import shape file
amaz.basin.shp <- st_read("~/Documents/Amazon_new_data/0. Amazon_shapefile/projected/amazon_shp_projected.shp")

# path of variables
burntArea.path <- "~/Documents/Amazon_new_data/1. Burnt Area/03. Working Data"
landCover.path <- "~/Documents/Amazon_new_data/2. Land Cover/03. Working Data"
precip.path <- "~/Documents/Amazon_new_data/3. Precipitation/03. Working Data"
soilMoisture.path <- "~/Documents/Amazon_new_data/4. Soil Moisture/03. Working Data"
elevation.path <- "~/Documents/Amazon_new_data/5. Elevation/03. Working Data"
LandSurfaceTemp.path <- "~/Documents/Amazon_new_data/6. LandSurfaceTemp/03. Working Data"
humidity.path <- "~/Documents/Amazon_new_data/7. Specific Humidity/03. Working Data"
evapotranspiration.path <- "~/Documents/Amazon_new_data/8. Evapotranspiration/03. Working Data"
wind.path <- "~/Documents/Amazon_new_data/9. Wind Speed/03. Working Data"
airtemp.path <- "~/Documents/Amazon_new_data/10. Air Temperature/03. Working Data"

x_min=-1.25e+06; x_max=0.05e+06; y_min=st_bbox(amaz.basin.shp)$ymin; y_max=2.4e+06    # South of Amazon

# Number of cores to use
# nbrCores <- detectCores() - 1
nbrCores <- 45

# Color palette
pal <- colorRampPalette(c("mediumblue", "forestgreen", "firebrick"))
pals <- unique(hypsometric_tints_db$pal)
```

#=====================

# Import data

```{r "1.Import data"}
#---- Burnt Area data ----
burntArea.rast <- 
  list.files(burntArea.path, full.names=TRUE, pattern = ".tif$") %>%
  rast()
#---- Land Cover ----
landCover.rast <- 
  list.files(landCover.path, full.names=TRUE, pattern = ".tif$") %>%
  rast()
#---- Precipitation ----
precipitation.rast <- 
  list.files(precip.path, full.names=TRUE, pattern = ".tif$") %>% 
  rast()
#----- Soil Moisture ----
soilMoisture.rast <- rast(paste0(my.path,"Amazon_new_data/4. Soil Moisture/soilmoisture_working_238.tif"))
#---- Elevation ----
elevation.rast <- 
  list.files(elevation.path,  full.names=TRUE, pattern = ".tif$")[1] %>%
  rast()
#---- LandSurfaceTemp ----
landSurfaceTemp.rast <- 
  list.files(LandSurfaceTemp.path, full.names=TRUE, pattern = ".tif$") %>% 
  rast()
#---- Specific Humidity ----
humidity.rast <- 
  list.files(humidity.path, full.names=TRUE, pattern = ".tif$") %>% 
  rast()
#---- Evapotranspiration ----
evapotranspiration.rast <- 
  list.files(evapotranspiration.path, full.names=TRUE, pattern = ".tif$") %>%
  rast()
#---- Wind Speed ----
wind.rast <- 
  list.files(wind.path, full.names=TRUE, pattern = ".tif$") %>%
  rast()
#---- Air Temperature ----
airtemp.rast <- 
  list.files(airtemp.path, full.names=TRUE, pattern = ".tif$") %>%
  rast()
```

# Modifications of "Soil Moisture"

```{r "2.Modifications"}
#----- Soil Moisture ----
# # Order layers
# ordered.names<- 
#   seq(as.Date("2001-1-1"), as.Date("2020-12-1"), by = "month") %>% 
#   format(., '%Y_%m') %>% 
#   setdiff(., c("2012_07", "2012_09"))
# soilMoisture.rast <- renameLayers(soilMoisture.rast, 'soilmoisture_working_', '')
# soilMoisture.rast <- soilMoisture.rast[[ordered.names]]
# # Repalce negative values by `NA` for all data
# soilMoisture.rast[soilMoisture.rast < 0] <- NA
# # Save/Load raster file
# writeRaster(soilMoisture.rast, "Amazon_new_data/4. Soil Moisture/soilmoisture_working_238.tif", overwrite=TRUE)
# soilMoisture.rast <- rast(paste0(my.path,"Amazon_new_data/4. Soil Moisture/soilmoisture_working_238.tif"))
```

# Rename and order layers

```{r}
ordered.names <- 
  seq(as.Date("2001-1-1"), as.Date("2020-12-1"), by = "month") %>%
  format(., '%Y_%m') %>% 
  setdiff(., c("2012_07", "2012_09"))
#---- Burnt Area data ----
burntArea.rast <- renameLayers(burntArea.rast, 'burntarea_working_', '')
burntArea.rast <- burntArea.rast[[ordered.names]]
#---- Land Cover ----
landCover.rast <- renameLayers(landCover.rast, 'landcover_working_', '')
landCover.rast <- landCover.rast[[ordered.names]]
#---- Precipitation ----
precipitation.rast <- renameLayers(precipitation.rast, 'precipitation_working_', '')
precipitation.rast <- precipitation.rast[[ordered.names]]
#----- Soil Moisture ----
# soilMoisture.rast <- renameLayers(soilMoisture.rast, 'soilmoisture_working_', '')
# names(soilMoisture.rast) <- ordered.names
#---- Elevation ----
names(elevation.rast) <- "elevation"
#---- LandSurfaceTemp ----
landSurfaceTemp.rast <- renameLayers(landSurfaceTemp.rast, 'landsurftemp_working_', '')
landSurfaceTemp.rast <- landSurfaceTemp.rast[[ordered.names]]
#---- Specific Humidity ----
humidity.rast <- renameLayers(humidity.rast, 'humidity_working_', '')
humidity.rast <- humidity.rast[[ordered.names]]
#---- Evapotranspiration ----
evapotranspiration.rast <- renameLayers(evapotranspiration.rast, 'evapotranspiration_working_', '')
evapotranspiration.rast <- evapotranspiration.rast[[ordered.names]]
#---- Wind Speed ----
wind.rast <- renameLayers(wind.rast, 'wind_working_', '')
wind.rast <- wind.rast[[ordered.names]]
#---- Air Temperature ----
airtemp.rast <- renameLayers(airtemp.rast, 'airtemp_working_', '')
airtemp.rast <- airtemp.rast[[ordered.names]]
```

# Create `rts` object

```{r}
# Dates
seq.dates <- seq(as.Date("2001-1-1"), as.Date("2020-12-1"), by = "month")
seq.dates <- seq.dates[!((seq.dates == "2012-07-01") | (seq.dates == "2012-09-01"))]
date.2020.12 <- seq(as.Date("2020-12-1"), as.Date("2020-12-1"), by = "month")
# Create 'rts' objects
burntArea.rts <- rts(burntArea.rast, seq.dates)
landCover.rts <- rts(landCover.rast, seq.dates)
precipitation.rts <- rts(precipitation.rast, seq.dates)
soilMoisture.rts <- rts(soilMoisture.rast, seq.dates)
elevation.rts <- rts(elevation.rast, date.2020.12)
landSurfaceTemp.rts <- rts(landSurfaceTemp.rast, seq.dates)
humidity.rts <- rts(humidity.rast, seq.dates)
evapotranspiration.rts <- rts(evapotranspiration.rast, seq.dates)
wind.rts <- rts(wind.rast, seq.dates)
airtemp.rts <- rts(airtemp.rast, seq.dates)
```

# Plot

## Burnt Area

```{r "1.1.Burnt Area"}
ba <- burntArea.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)  
levels(ba) <- data.frame(id=c(-2, 0, 1), cover=c('-2', '0', '1'))
my.colors <- c("mediumblue", "mediumseagreen", "firebrick")
myPlot(ba) +
  scale_fill_manual(name = "Burnt Area", values = my.colors, na.translate=FALSE)
```

```{r "1.2.Q1", message=F}
Q1 <- rast("~/Documents/Amazon_new_data/1. Burnt Area/ras/Q1_238.tif") 
levels(Q1) <- data.frame(id=c(-2, 0, 1), cover=c('-2', '0', '1'))
my.colors <- c("mediumblue", "mediumseagreen", "firebrick")
myPlot(Q1, "Maximum value for each cell") +
  scale_fill_manual(name = "Burnt Area", values = my.colors, na.translate=FALSE)
```

## Land Cover

```{r "2.1.Land Cover", message=F}
lc <- landCover.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)  
levels(lc) <- data.frame(id=0:10, cover=c('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'))
myPlot(lc) + 
  scale_fill_hypso_d(
    name = "Land Cover", 
    palette = "colombia_hypso", 
    na.translate=FALSE)
```

## Precipitation

```{r "3.1.Precipitation", message=F}
prec <- precipitation.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)
myPlot(prec) + 
  scale_fill_scico(
    name = TeX(r"(Precipitation $\textit{(mm/hr)}$)"),
    palette = "lapaz", 
    direction = -1,
    trans = "pseudo_log",
    breaks = c(0,10,50,100,250,550),
    na.value = "transparent")
```

## Soil Moisture

```{r "4.1.Soil Moisture"}
soilm <- soilMoisture.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)
myPlot(soilm) + 
  scale_fill_hypso_c(
    name = TeX(r"(Soil Moisture $\textit{(mm)}$)"),
    palette = "wiki-schwarzwald-cont", 
    na.value = "transparent")
```

## Elevation

```{r "5.1.Elevation", message=F}
elev <- elevation.rts[['2020-12-01']] %>% mask(mask = amaz.basin.shp)
wikicols <- hypsometric_tints_db %>% filter(pal == "wiki-2.0")
wikicols <- wikicols[wikicols$limit %between% c(-100, 6500),]
myPlot(elev) + 
  scale_fill_gradientn(
    name = TeX(r"(Elevation $\textit{(m)}$)"),
    colors = wikicols$hex,
    values = scales::rescale(wikicols$limit),
    limit = range(wikicols$limit),
    na.value = "transparent")
```

## LandSurfaceTemp

```{r "6.1.LandSurfaceTemp", message=F}
lst <- landSurfaceTemp.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)
myPlot(lst) +
  scale_fill_whitebox_c(
    name = TeX(r"(Land Surface Temperature $\textit{(K)}$)"),
    palette = "muted", 
    na.value = "transparent")
```

## Specific Humidity

```{r "7.1.Specific Humidity", message=F}
hum <- humidity.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)
myPlot(hum) +
  scale_fill_cross_blended_c(
    name = TeX(r"(Humidity $\textit{(kg_{water} / kg_{air})}$)"),
    palette = "warm_humid", 
    na.value = "transparent")
```

## Evapotranspiration

```{r "8.1.Evapotranspiration", message=F}
evapot <- evapotranspiration.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)
myPlot(evapot) +
  scale_fill_whitebox_c(
    name = TeX(r"(Evapotranspiration $\textit{(kg/m^2s)}$)"),
    palette = "bl_yl_rd", 
    na.value = "transparent")
```

## Wind Speed

```{r "9.1.Wind Speed", message=F}
wind <- wind.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)
myPlot(wind) +
  scale_fill_hypso_c(
    name = TeX(r"(Wind Speed $\textit{(m / s)}$)"),
    palette = "gmt_globe_bathy", 
    trans = "pseudo_log",
    direction = -1,
    na.value = "transparent")
```

## Air Temperature

```{r "10.1.Air Temperature", message=F}
airtemp <- airtemp.rts[['2020-10-01']] %>% mask(mask = amaz.basin.shp)
myPlot(airtemp) +
  scale_fill_whitebox_c(
    name = TeX(r"(Air Temperature $\textit{(K)}$)"),
    palette = "bl_yl_rd", 
    na.value = "transparent")
```

# Create and plot zones

```{r}
v <- ext(amaz.basin.shp)
x.min <- v$xmin[[1]] - 1; x.max <- v$xmax[[1]] + 1; 
y.min <- v$ymin[[1]] - 1; y.max <- v$ymax[[1]] + 1; 

XY <- list(
  c(x.min, -0.84e+06, y.min, y.max),                       # z1
  c(-0.84e+06, +0.55e+06, 3.75e+06, y.max),                # z2
  c(-0.84e+06, +0.55e+06, 2.6e+06, 3.75e+06),              # z3
  c(-0.84e+06, -0.05e+06, 2.22e+06, 2.6e+06),              # z4
  c(-0.84e+06, -0.51e+06, y.min, 2.22e+06),                # z5
  c(-0.51e+06, -0.05e+06, y.min, 2.22e+06),                # z6
  c(-0.05e+06, 0.6e+06, y.min, 2.6e+06),                   # z7
  c(0.6e+06, 0.95e+06, y.min, 2.6e+06),                    # z8
  c(+0.55e+06, x.max, 3.24e+06, y.max),                    # z9
  c(+0.55e+06, x.max, 2.86e+06, 3.24e+06),                 # z10
  c(+0.55e+06, 0.95e+06, x.max, y.min, 2.6e+06, 2.86e+06)  # z11
)

nz <- length(XY)
zl <- list()
for (i in 1:(nz-1)){
  zl[[i]] <- rbind(
    c(XY[[i]][1], XY[[i]][3]), 
    c(XY[[i]][2], XY[[i]][3]), 
    c(XY[[i]][2], XY[[i]][4]), 
    c(XY[[i]][1], XY[[i]][4])
  ) %>% 
    cbind(object=i, part=1, ., hole=0) %>% 
    as.data.table()
}

i <- nz
zl[[i]] <- rbind(
  c(XY[[i]][2], XY[[i]][4]), 
  c(XY[[i]][3], XY[[i]][4]), 
  c(XY[[i]][3], XY[[i]][6]), 
  c(XY[[i]][1], XY[[i]][6]), 
  c(XY[[i]][1], XY[[i]][5]), 
  c(XY[[i]][2], XY[[i]][5])
) %>% 
  cbind(object=i, part=1, ., hole=0) %>% 
  as.data.table()

z <- rbindlist(zl, use.names=T) %>% as.matrix()
colnames(z)[3:4] <- c('x', 'y')

p <- vect(z, "polygons")
crs(p) <- crs(amaz.basin.shp)

#---- Plot ----
my.labels <-  c( 'z1',      'z2',      'z3',     'z4',     'z5',     'z6',     'z7',     'z8',     'z9',   'z10',     'z11')
x.coor <- c(-1.50e+06, -0.50e+06, -0.50e+06, -0.5e+06, -0.70e+06, -0.20e+06, 0.30e+06,  0.8e+06, 1.30e+06, 1.60e+06, 1.30e+06)
y.coor <- c( 3.05e+06,  4.05e+06,  3.05e+06,  2.4e+06,  1.85e+06,  1.85e+06, 2.05e+06, 2.05e+06, 4.05e+06, 3.05e+06, 2.55e+06)

ggplot()  +
  geom_spatvector(data = amaz.basin.shp$geometry, fill = 'white', color = "gray40") +
  geom_spatraster(data = Q1) +
  geom_spatvector(data = p, fill = NA, color = "black") +
  scale_x_continuous(labels = function(x) format(x, scientific = T)) +
  scale_y_continuous(labels = function(x) format(x, scientific = T)) +
  coord_sf(datum = pull_crs(Q1)) + 
  ggtitle("Plot of the maximum value for each cell") +
  theme_bw() +
  scale_fill_manual(name = "Burnt Area", values = alpha(my.colors, 0.75), na.translate=FALSE) +
  annotate("text", label = my.labels, x = x.coor, y = y.coor, size = 4, colour = "black")
```








































