---
title: "Amazon_prepare_data"
date: "2023-05-26"
output:
  html_document: 
    number_sections: yes
    fig_caption: yes
    toc: true
    toc_float: 
      collapsed: false
    theme: cerulean
    highlight: kate
    toc_depth: 5
    keep_md: yes
    df_print: paged
---



# Load libraries

```{r warning=FALSE, message=FALSE}
library(terra)
library(sf)
# library(tidyverse)
library(data.table)
library(dplyr)
library(gdata)
library(pROC)
# Parallel
library(foreach)
library(doSNOW)
library(parallel)
library(itertools)
# Cross Validation
library(rsample)
library(recipes)
# Plot
library(RColorBrewer)
library(tidyterra)
library(scico)
library(wesanderson)
library(viridis)
library(scales)
# library(latex2exp)
library(ggplot2)
library(plotly)
# Time
library(tictoc)
library(gdata)
```


# Functions

```{r "Functions"}
# ==== Function to rename layers ====

renameRast <- function(dataRast, fileStart, prefix){
  library(data.table)
  # index of file name in the path
  id.date <- unlist(gregexpr(fileStart, sources(dataRast)[[1]])) + nchar(fileStart)
  # rename layers
  dateRast <- 
    substr(sources(dataRast), id.date, (id.date+50)) %>%
    gsub(".tif", "_1", .) %>%
    as.Date("%Y_%m_%d")
  # Rename layers
  names(dataRast) <- 
    dateRast %>%
    format(., '%Y_%m') %>%
    paste0(prefix, .)
  yearRast <- data.table::year(dateRast)
  monthRast <- data.table::month(dateRast)
  # return
  return(list(dataRast, yearRast, monthRast))
}

# ==== Split zones ====

splitAmaZones <- function(Amazon.data.dt, amaz.basin){
  #---- Initialization of zones ----
  amaz.basin.shp <- st_read(paste0(path0, "/Amazon_new_data/0. Amazon_shapefile/projected/amazon_shp_projected.shp"), quiet = TRUE)

  v <- ext(amaz.basin.shp)
  x.min <- v$xmin[[1]] - 1; x.max <- v$xmax[[1]] + 1; 
  y.min <- v$ymin[[1]] - 1; y.max <- v$ymax[[1]] + 1; 
  #
  XY <- list(
    c(x.min, -0.84e+06, y.min, y.max),                                    # z1
    c(-0.84e+06, +0.55e+06,  3.75e+06,     y.max),                        # z2
    c(-0.84e+06, +0.55e+06,  2.60e+06,  3.75e+06),                        # z3
    c(-0.84e+06, -0.05e+06,  2.22e+06,  2.60e+06),                        # z4
    c(-0.84e+06, -0.51e+06,     y.min,  2.22e+06),                        # z5
    c(-0.51e+06, -0.05e+06,     y.min,  2.22e+06),                        # z6
    c(-0.05e+06,  0.60e+06,     y.min,  2.60e+06),                        # z7
    c( 0.60e+06,  0.95e+06,     y.min,  2.60e+06),                        # z8
    c(+0.55e+06,     x.max,  3.24e+06,     y.max),                        # z9
    c(+0.55e+06,     x.max,  2.86e+06,  3.24e+06),                        # z10
    c(+0.55e+06,  0.95e+06,     x.max,      y.min,  2.60e+06,  2.86e+06)  # z11
  )
  #---- Create column `Zones` ----
  Amazon.data.dt[, Zones := 0.0]
  Amazon.data.dt %>% setcolorder(., c('cell', 'x', 'y', 'Zones', 'Year', 'Month')) %>% as.data.table()
  nz <- length (XY)
  #---- Split the data ----
  for (i in 1:nz){
    # cat("Zone", i, "/", nz, " - ")
    if (i == nz){
      # Polygon
      Amazon.data.dt[((x > XY[[i]][2] & x <= XY[[i]][3]) & (y > XY[[i]][4] & y <= XY[[i]][5])) | 
                       ((x > XY[[i]][1] & x <= XY[[i]][3]) & (y > XY[[i]][5] & y <= XY[[i]][6])), Zones := i]
    }else{
      # Rectangle
      Amazon.data.dt[(x > XY[[i]][1] & x <= XY[[i]][2]) & (y > XY[[i]][3] & y <= XY[[i]][4]), Zones := i]
    }
  }
  #---- Compute the number of cells in each zone ----
  dim.zones <- Amazon.data.dt[, .N, by=.(Zones)]
  dim.zones[order(Zones)]
  return(Amazon.data.dt)
}
```

# Initialization

```{r}
my.path <- "/Users/ABIDM/Documents/Project/Code_official_data"
path0 <- "/Users/ABIDM/Documents/Project/Code_official_data"
path0 <- "/home/abidm/Documents"
# Import shape file
amaz.basin.shp <- st_read(paste0(path0, "/Amazon_new_data/0. Amazon_shapefile/projected/amazon_shp_projected.shp"), quiet = TRUE)

# path of variables
burntArea.path <- paste0(path0, "/Amazon_new_data/1. Burnt Area/03. Working Data")
landCover.path <- paste0(path0, "/Amazon_new_data/2. Land Cover/03. Working Data")
precip.path <- paste0(path0, "/Amazon_new_data/3. Precipitation/03. Working Data")
soilMoisture.path <- paste0(path0, "/Amazon_new_data/4. Soil Moisture/03. Working Data")
elevation.path <- paste0(path0, "/Amazon_new_data/5. Elevation/03. Working Data")
LandSurfaceTemp.path <- paste0(path0, "/Amazon_new_data/6. LandSurfaceTemp/03. Working Data")
humidity.path <- paste0(path0, "/Amazon_new_data/7. Specific Humidity/03. Working Data")
evapotranspiration.path <- paste0(path0, "/Amazon_new_data/8. Evapotranspiration/03. Working Data")
wind.path <- paste0(path0, "/Amazon_new_data/9. Wind Speed/03. Working Data")
airtemp.path <- paste0(path0, "/Amazon_new_data/10. Air Temperature/03. Working Data")

# Color palette
my.colors <- c("mediumblue", "mediumseagreen", "firebrick")
pal <- colorRampPalette(c("mediumblue", "mediumseagreen", "firebrick"))

# Create a sequence of dates
sq.date <- seq(as.Date("2001-1-1"), as.Date("2020-12-1"), by = "month") %>% 
  format(., '%Y_%m') %>% 
  setdiff(., c("2012_07", "2012_09"))
```

#======================

```{r}
#---- Load data ----
path.ras0 <- paste0(path0, "/Amazon_new_data/1. Burnt Area/03. Working Data/burntarea_working_2001_1.tif")
var0.ras <- rast(path.ras0) %>% mask(mask = amaz.basin.shp)
values(var0.ras) <- -1
var0.dt <- as.data.table(var0.ras, cell=T, xy=T) # 95.344 sec
rm(var0.ras); gc()
# n.month <- 0
sq.date <- c("2007_02", "2009_05", "2019_08", "2020_10")
for(n.month in sq.date){ 
  # n.month <- n.month + 12 # n.month <- 49
  # n.month <- "2017_01"
  tic()
  y_m <- c()
  y_m[1] <- sub("_.*", "", n.month)
  y_m[2] <- sub(".*_0", "", n.month) %>% sub(".*_", "", .)
  
  amaz.var.list <- c(
    paste0(burntArea.path, '/burntarea_working_', y_m[1], '_', y_m[2], '.tif')
    , paste0(landCover.path, '/landcover_working_', y_m[1], '_', y_m[2], '.tif')
    , paste0(precip.path, '/precipitation_working_', y_m[1], '_', y_m[2], '.tif')
    , paste0(soilMoisture.path, '/soilmoisture_working_', y_m[1], '_', y_m[2], '.tif')
    , paste0(elevation.path, '/elevation_working_', y_m[1], '_', sub(".*_", "", n.month) , '.tif')
    # , paste0(elevation.path, '/elevation_working.tif')
    , paste0(LandSurfaceTemp.path, '/landsurftemp_working_', y_m[1], '_', y_m[2], '.tif')
    , paste0(humidity.path, '/humidity_working_', y_m[1], '_', y_m[2], '.tif')
    , paste0(evapotranspiration.path, '/evapotranspiration_working_', y_m[1], '_', y_m[2], '.tif')
    , paste0(wind.path, '/wind_working_', y_m[1], '_', y_m[2], '.tif')
    , paste0(airtemp.path, '/airtemp_working_', y_m[1], '_', y_m[2], '.tif')
  )
  amaz.basin.shp <- st_read(paste0(path0, "/Amazon_new_data/0. Amazon_shapefile/projected/amazon_shp_projected.shp"), quiet = TRUE)
  
  #---- Prepare data ---- 
  # tic("Prepare data") 
  # nbr.z <- 11 # number of zones
  # Create 'SpatRaster' object
  var.ras <- rast(amaz.var.list) %>% mask(mask = amaz.basin.shp) # 21.236 sec
  names(var.ras) <- c('BurntArea', 'LandCover', 'Precipitation', 'SoilMoisture', 'Elevation', 'LandSurfaceTemp', 'Humidity', 'Evapotranspiration', 'Wind', 'AirTemp')
  var.ras[[c('BurntArea', 'SoilMoisture')]][var.ras[[c('BurntArea', 'SoilMoisture')]] < 0] <- NA # 14.716 sec
  
  # Prepare data table
  # system.time({
    var1.dt <- terra:::as.matrix(var.ras, cell=T, xy=T) %>% as.data.table()
    var1.dt[,c('cell', 'x', 'y') := var0.dt[, 1:3]]
  # }) # 28.435 sec
  var.dt <- var1.dt %>% 
    mutate(
      x = floor(x),
      y = floor(y),
      Year = rep(y_m[1], dim(var1.dt)[1]) %>% as.factor(),
      Month = rep(y_m[2], dim(var1.dt)[1]) %>% as.factor(),
      BurntArea = as.factor(BurntArea),
      LandCover = as.factor(LandCover)
    ) %>%
    na.omit() %>%
    setcolorder(., c('cell', 'x', 'y', 'Year', 'Month'))
  
  var.zones.dt <- splitAmaZones(var.dt)
  var.zones.dt$Zones <- as.factor(var.zones.dt$Zones)
  # toc() # 176.63 sec elapsed
  rm(var.ras, var1.dt, var.dt); gc()
  
  #---- Normalize data ----
  # tic("Normalize data") 
  AZ_recipe <- recipe( BurntArea ~ ., data = var.zones.dt) %>% 
    step_normalize(all_numeric(), -c(cell, x, y))
  
  var.norm <- AZ_recipe %>% 
    prep() %>% 
    bake(new_data = NULL) %>% 
    setcolorder(., c('Zones', 'cell', 'x', 'y', 'Year', 'Month', 'BurntArea')) %>% 
    as.data.table()
  # toc() # Normalize data: 14.198 sec elapsed
  
  save(var.norm, file = paste0(path0, "/Amazon_new_data/DT/amazon_dt_", n.month, ".Rdata")) # 40.669 sec
  toc() # 319.717 sec elapsed ~ 5.4 min
  #
  rm(var.zones.dt, var.norm, AZ_recipe); gc()
}
# load(paste0(path0, "/Models_ens/Ens3/ENS3_pred.Rdata"))
```

```{r}
load(paste0(path0, "/Amazon_new_data/DT/amazon_dt_", n.month, ".Rdata")) # 6.059 sec
```











































































