---
title: "V-fold Cross Validation"
output: html_document
date: "2023-03-14"
---

https://rpubs.com/ngyongkad/crossvalidation

```{r}
library(tidyverse)
library(janitor)

data <- read.csv("https://github.com/ngyongkad/scorecard/blob/main/Import%20Credit%20Card%20Defaults.csv?raw=true")  

# change the variable names to lower case 
# rename the default indicator and convert it into factor
data <- clean_names(data) %>%
  rename(gb_flag = default_payment_next_month) %>%
  mutate(gb_flag = as.factor(gb_flag))
```

```{r}
init_samp <- data %>%
 select(gb_flag, bill_amt1:bill_amt6)

obs_num <- nrow(init_samp)
var_num <- ncol(init_samp %>% select(bill_amt1:bill_amt6)) - 1 

# create a loop to calculate average bill_amt
amt <- as_tibble(matrix(NA, obs_num, var_num))

for (i in seq_along(1:var_num)) {
  j <- i + 2
  amt[, i] <- apply(init_samp[2:j], 1, mean)
  names(amt)[i] <- str_c("avg_bill_amt_last_", i + 1, "_mth")
}

# combine with the default indicator
init_samp_var <- bind_cols(amt, init_samp %>% select(gb_flag))
```

```{r}
table(init_samp_var$gb_flag)
```

# Sample Splitting

```{r}
library(tidymodels)

set.seed(123)
split <- initial_split(init_samp_var, prop = 0.75, strata = gb_flag)

# display the split
split
```

```{r}
training(split)
testing(split)
```

```{r}
# development sample
devop <- training(split) 

# create 10-fold cross validation samples 
set.seed(456)
folds <- vfold_cv(devop, v = 10,  strata = gb_flag)

# display the 10 folds
folds
```

```{r}
a <- analysis(folds$splits[[1]])
a
table(a$gb_flag)

```


# 10-fold Cross Validation

```{r}
## load the packages 
library(tidymodels)
library(scorecard)

## set up the necessary helper functions

# extraction function for pulling IV
extract_iv <- function(x) {
  map_df(x, ~ pluck(., 10, 1))  # 10 is the location of total IV 
}

# extraction function for pulling break points 
extract_blist <- function(x) {
  map(x, ~ pluck(., 11)) # 11 is the location of break list 
}

# cleaning function that removes "Inf" from break list
remove_inf <- function(x) {
  rmv <- function(x, y) {
    x[-y]
  }
  y <- map(x, length) # iterate over all of the elements in the list x
  map2(x, y, ~ rmv(.x, .y))
}
```

```{r}
# obtain the cross validated IV values from the training sample
train_cv <- folds %>%  
  mutate(cv_train    = map(splits, analysis), 
         woe_train   = map(cv_train, ~ woebin(., y = "gb_flag", method = "freq", bin_num_limit = 20, positive = "1")),
         iv_train    = map(woe_train, extract_iv),
         blist_long  = map(woe_train, extract_blist), 
         blist_short = map(blist_long, remove_inf) # pass the break points for use in the testing sample
        ) 

# obtain the cross validated IV values from the testing sample
test_cv <- train_cv %>% 
  select(splits, id, blist_short) %>%
  mutate(cv_test  = map(splits, assessment), 
         woe_test = map2(cv_test, blist_short, ~ woebin(.x, y = "gb_flag", method = "freq", positive = "1", breaks_list = .y)),
         iv_test  = map(woe_test, extract_iv))

# tidy the IVs from the testing sample
test_iv_summary <- test_cv %>% 
  select(id, iv_test) %>%
  unnest(cols = iv_test) %>%
  summarise(across(-id, mean, .names="{.col}_iv_mean")) %>%
  pivot_longer(everything(), names_to = "var", values_to = "iv_mean")
```

```{r}
# visuallize the results 
test_iv_summary %>%
  mutate(var = str_remove_all(var, "bill_amt_|_iv_mean")) %>%
  ggplot(mapping = aes(x = var, y = iv_mean)) +
  geom_bar(fill = "darkblue", stat = "identity")
```













